[manifest]
version = "1.0.0"
priority = -2

# cIKIRS
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
                    {name = 'colour_1', ref_table = G.C, ref_value = 'BLUE'},
                    {name = 'colour_2', ref_table = G.C, ref_value = 'WHITE'},
'''
position = "at"
payload = ''' 
                    {name = 'colour_1', ref_table = G.C, ref_value = 'PURPLE'},
                    {name = 'colour_2', ref_table = G.C, ref_value = 'FILTER'},
'''
match_indent = true

# aKK THE CARDS FLYING
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''card_size*G.CARD_W, card_size*G.CARD_H, pseudorandom_element(G.P_CARDS), G.P_CENTERS.c_base)'''
position = "at"
payload = ''' 
card_size*G.CARD_W, card_size*G.CARD_H, pseudorandom_element(G.P_CENTER_POOLS.BitterPool), G.P_CENTERS.c_base)
'''
match_indent = true

# bitterdoes
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = "SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_joker'])"
position = "at"
payload = '''
SC = Card(G.ROOM.T.w/2 - SC_scale*G.CARD_W/2, 10. + G.ROOM.T.h/2 - SC_scale*G.CARD_H/2, SC_scale*G.CARD_W, SC_scale*G.CARD_H, G.P_CARDS.empty, G.P_CENTERS['j_Bitters_bitterjoker'],{bypass_discovery_center = true, bypass_discovery_ui = true})
'''
match_indent = true