[manifest]
version = "1.0.0"
priority = 0

# colors
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
            {name = 'colour_1', ref_table = G.C, ref_value = 'RED'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'BLUE'},
'''
position = "at"
payload = ''' 
            {name = 'colour_1', ref_table = G.C, ref_value = 'FILTER'},
            {name = 'colour_2', ref_table = G.C, ref_value = 'PURPLE'},
'''
match_indent = true

# bitter does
[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.S_A, G.P_CENTERS.c_base)'''
position = "at"
payload = ''' 
local replace_card = Card(self.title_top.T.x, self.title_top.T.y, 1.2*G.CARD_W*SC_scale, 1.2*G.CARD_H*SC_scale, G.P_CARDS.empty, G.P_CENTERS['j_Bitters_bitterjoker'])
'''
match_indent = true